### ISSUE TITLE
RcppRedis is version unaware

### ISSUE THREAD

**Issue by russellpierce** [eddelbuettel/rcppredis#18]
Redis keeps adding new functions, e.g. PEXPIRE is only available since 2.6.0.  We should probably check the version of the Redis server we connect to and disallow calls to functions that aren't available.  Preferably, we would throw a warning.  Ideally we'd simulate the desired effect.  For example, a call to PEXPIRE could just round to the nearest full second and call EXPIRE with a warning.

**Comment by eddelbuettel** [comment]
Could do. We would need to keep track of what which version needs and have a "meta" structure.  It sort of goes against the otherwise 'keep it simple, minimal' approach we have.   But more robust is better.

Also, if say 2.6 is the minimal requirement:  how likely is really to have an older Redis out there in the wild?

**Comment by drknexus** [comment]
I'm okay with 2.6 being set as a minimal version.  Too bad 2.8.13 isn't more in the wild; http://redis.io/commands/command seems like it might be perfect for doing command validation against; we could just, for example, get the meta structure at connect time.

**Comment by eddelbuettel** [comment]
Oh, I like that trick a lot.   And 2.8 minimum is ok by me too -- need to update to 3.0 at work these days, and we have one custom patch I need to apply.

**Comment by eddelbuettel** [comment]
Closing as stale.
